name: Deploy to Sever # 名字随意
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 21.x
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # 令 GitHub 在 git clone 和 git checkout 后「忘记」使用的 credentials。
          # 如果之后需要以另外的身份（如你的 GitHub Bot）执行 git push 操作时（如部署到 GitHub Pages），必须设置为 false。
          persist-credentials: false
          submodules: true
      - name: Set Timezone
        run: |
          export TZ='Asia/Shanghai'
      # 这里是为了将站点部署到服务器
      # 当然你也可以使用其他的部署方式，如部署到 Cloudflare Pages 等
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # 这里的 SSH_PRIVATE_KEY 是你在 GitHub Secrets 中设置的私钥
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          # 如果你只需要连接到特定的服务器，你可以在 Secrets 设置 known_hosts，将机器的公钥添加到 known_hosts 中即可
          # 如果你不想使用 known_hosts，你可以将 SSH_KNOWN_HOSTS 设置为 unnecessary
          # https://github.com/shimataro/ssh-key-action
          # https://stackoverflow.com/questions/34906302/add-public-key-to-known-hosts-file
      - name: Install ssh config
        run: |
          echo ${{ secrets.SSH_CONFIG }} >> ~/.ssh/config
          chmod 600 ~/.ssh/config
      - name: Deploy to Server
        run: |
          ssh -t lab-deployer "
          cd ~/lab && git pull &&
          pnpm install &&
          pnpm build && systemctl --user restart lab-webserver.service
          "
      - name: Notify
        run: |
          curl https://${{ secrets.NTFY_HOST }} \
          -H "Authorization: Bearer ${{ secrets.NTFY_TOKEN }}" \
          -d '{
              "topic": "me",
              "message": "快来查看吧",
              "title": "实验室已成功部署",
              "tags": ["bell"],
              "priority": 4,
              "click": "https://lab.gb0.dev",
              "actions": [{ "action": "view", "label": "查看", "url": "https://lab.gb0.dev" }]
          }'
            